# -*- Makefile -*-

# --------------------------------------------------------------------
TESTS ?= eclib mlkem

# --------------------------------------------------------------------
.PHONY: default

default:
	easycrypt runtest tests.config $(TESTS)
